import type { ExecutionEvent } from '../types';

export const executionEvents: ExecutionEvent[] = [
  { id: 'ev-1', fieldUpdateId: 'fu-1', activityDescription: 'Structural steel Bay 1 erection', location: 'Bay 1', progressPercent: 90, reportedDate: '2026-07-08', evidence: { sourceId: 'dpr-2026-07-08', sourceType: 'dpr', excerpt: 'Structural steel Bay 1 erection substantially complete, touch-up welding remaining.', page: 2 } },
  { id: 'ev-2', fieldUpdateId: 'fu-2', activityDescription: 'Pipe rack erection', location: 'Pipe rack', progressPercent: 60, reportedDate: '2026-07-18', evidence: { sourceId: 'dpr-2026-07-18', sourceType: 'dpr', excerpt: 'Pipe rack erection at 60% - columns and first two tiers set.', page: 1 } },
  { id: 'ev-3', fieldUpdateId: 'fu-3', activityDescription: 'Line 24 erection', location: 'Line 24', progressPercent: 45, reportedDate: '2026-08-03', evidence: { sourceId: 'sms-2026-08-03', sourceType: 'text', excerpt: 'Line 24 erection at 45% today.' } },
  { id: 'ev-4', fieldUpdateId: 'fu-4', activityDescription: 'Spool erected, Line 24', location: 'Line 24', progressPercent: 50, reportedDate: '2026-08-02', evidence: { sourceId: 'sms-2026-08-02', sourceType: 'text', excerpt: 'Spool erected for Line 24, roughly halfway through the run.' } },
  { id: 'ev-5', fieldUpdateId: 'fu-5', activityDescription: 'Pipe work near pump skid', progressPercent: 60, reportedDate: '2026-08-04', evidence: { sourceId: 'voice-2026-08-04', sourceType: 'voice', excerpt: 'Crew reports pipe work near the pump skid substantially done, 60% by their count.' } },
  { id: 'ev-6', fieldUpdateId: 'fu-6', activityDescription: 'Demo of legacy scaffold tower', location: 'Bay 3', progressPercent: 20, reportedDate: '2026-08-05', evidence: { sourceId: 'sms-2026-08-05', sourceType: 'text', excerpt: 'New scope: contractor started demo of legacy scaffold tower near Bay 3, not on baseline schedule.' } },
  { id: 'ev-7', fieldUpdateId: 'fu-7', activityDescription: 'Foundation concrete pour Area A', location: 'Area A', progressPercent: 100, reportedDate: '2026-06-25', evidence: { sourceId: 'dpr-2026-06-25', sourceType: 'dpr', excerpt: 'Foundation concrete pour Area A complete, cured, forms stripped.', page: 1 } },
  { id: 'ev-8', fieldUpdateId: 'fu-8', activityDescription: 'Foundation excavation Area B', location: 'Area B', progressPercent: 100, reportedDate: '2026-06-13', evidence: { sourceId: 'xls-progress-wk24', sourceType: 'excel', excerpt: 'Excavation Area B: 100% complete, backfilled and compacted.' } },
  { id: 'ev-9', fieldUpdateId: 'fu-9', activityDescription: 'Vessel setting Unit 100', location: 'Unit 100', progressPercent: 55, reportedDate: '2026-07-14', evidence: { sourceId: 'xls-progress-wk29', sourceType: 'excel', excerpt: 'Vessel setting Unit 100: 55% complete.' } },
  { id: 'ev-10', fieldUpdateId: 'fu-10', activityDescription: 'Electrical cable tray installation', location: 'Unit 100', progressPercent: 100, reportedDate: '2026-09-20', evidence: { sourceId: 'sms-2026-09-20', sourceType: 'text', excerpt: 'Electrical cable tray L5.4.1 reported complete on 2026-09-20.' } },
];
