import type { ExecutionEvent } from '../types';

export const executionEvents: ExecutionEvent[] = [
  { id: 'ev-1', fieldUpdateId: 'fu-1', activityDescription: 'P104 24-inch spool erected at Rack 3', location: 'Rack 3', progressPercent: 100, reportedDate: '2026-06-10', evidence: { sourceId: 'dpr-2026-06-10', sourceType: 'dpr', excerpt: 'P104 24-inch spool erected at Rack-3.', page: 2 } },
  { id: 'ev-2', fieldUpdateId: 'fu-2', activityDescription: 'All P104 pipe supports fixed at Rack 3', location: 'Rack 3', progressPercent: 100, reportedDate: '2026-06-06', evidence: { sourceId: 'dpr-2026-06-06', sourceType: 'dpr', excerpt: 'All P104 pipe supports at Rack 3 have been fixed.', page: 1 } },
  { id: 'ev-3', fieldUpdateId: 'fu-3', activityDescription: 'P104 spool erected', location: 'Rack 4', progressPercent: 50, reportedDate: '2026-06-11', evidence: { sourceId: 'sms-2026-06-11', sourceType: 'text', excerpt: 'P104 spool erected at Rack-4.' } },
  { id: 'ev-4', fieldUpdateId: 'fu-4', activityDescription: 'P104 erection', location: 'Rack 3', progressPercent: 60, reportedDate: '2026-06-11', evidence: { sourceId: 'sms-2026-06-11b', sourceType: 'text', excerpt: 'P104 erection at Rack 3 is 60% complete.' } },
  { id: 'ev-5', fieldUpdateId: 'fu-5', activityDescription: 'P104 erection', location: 'Rack 3', progressPercent: 45, reportedDate: '2026-06-12', evidence: { sourceId: 'voice-2026-06-12', sourceType: 'voice', excerpt: 'P104 erection at Rack 3 is 45% complete.' } },
  { id: 'ev-6', fieldUpdateId: 'fu-6', activityDescription: 'Scaffolding erected around Rack 3', location: 'Rack 3', progressPercent: 20, reportedDate: '2026-06-12', evidence: { sourceId: 'sms-2026-06-12', sourceType: 'text', excerpt: 'Scaffolding erected around Rack 3, not on baseline schedule.' } },
  { id: 'ev-7', fieldUpdateId: 'fu-7', activityDescription: 'T201 foundation casting finished', location: 'Tank Farm', progressPercent: 100, reportedDate: '2026-06-09', evidence: { sourceId: 'dpr-2026-06-09', sourceType: 'dpr', excerpt: 'T201 foundation casting finished today.', page: 1 } },
  { id: 'ev-8', fieldUpdateId: 'fu-8', activityDescription: 'Excavation for tank T-201 foundation started', location: 'Tank Farm', progressPercent: 30, reportedDate: '2026-06-01', evidence: { sourceId: 'xls-progress-wk1', sourceType: 'excel', excerpt: 'Excavation for tank T-201 foundation started.' } },
  { id: 'ev-9', fieldUpdateId: 'fu-9', activityDescription: 'P105 spool erected', location: 'Rack 3', progressPercent: 100, reportedDate: '2026-06-10', evidence: { sourceId: 'xls-progress-wk2', sourceType: 'excel', excerpt: 'P105 spool erected at Rack 3.' } },
  { id: 'ev-10', fieldUpdateId: 'fu-10', activityDescription: 'Cable pulling in Substation B finished', location: 'Substation B', progressPercent: 100, reportedDate: '2026-06-14', evidence: { sourceId: 'sms-2026-06-14', sourceType: 'text', excerpt: 'Cable pulling in Substation B finished.' } },
  { id: 'ev-11', fieldUpdateId: 'fu-11', activityDescription: 'Rack 3 piping erection started', location: 'Rack 3', progressPercent: 10, reportedDate: '2026-06-10', evidence: { sourceId: 'sms-2026-06-10', sourceType: 'text', excerpt: 'Rack 3 piping erection started.' } },
  { id: 'ev-12', fieldUpdateId: 'fu-12', activityDescription: 'P208 painting completed', location: 'Tank Farm', progressPercent: 100, reportedDate: '2026-06-15', evidence: { sourceId: 'sms-2026-06-15', sourceType: 'text', excerpt: 'P208 painting completed in Tank Farm.' } },
  { id: 'ev-13', fieldUpdateId: 'fu-13', activityDescription: 'P104 supports complete and spool erection started', location: 'Rack 3', progressPercent: 50, reportedDate: '2026-06-08', evidence: { sourceId: 'dpr-2026-06-08', sourceType: 'dpr', excerpt: 'P104 supports are complete and spool erection started at Rack 3.', page: 1 } },
  { id: 'ev-14', fieldUpdateId: 'fu-14', activityDescription: 'P104 erctn done', location: 'Rack 3', progressPercent: 30, reportedDate: '2026-06-11', evidence: { sourceId: 'sms-2026-06-11c', sourceType: 'text', excerpt: 'P-104 erctn done at R-3.' } },
  { id: 'ev-15', fieldUpdateId: 'fu-15', activityDescription: 'Twenty-four inch header now in place', location: 'Rack 3', progressPercent: 40, reportedDate: '2026-06-10', evidence: { sourceId: 'voice-2026-06-10', sourceType: 'voice', excerpt: 'The twenty-four inch header near rack three is now in place.' } },
  { id: 'ev-16', fieldUpdateId: 'fu-16', activityDescription: 'Rack piping completed for the week', location: 'Rack 3', progressPercent: 35, reportedDate: '2026-06-12', evidence: { sourceId: 'dpr-2026-06-12', sourceType: 'dpr', excerpt: 'Rack piping completed for the week.', page: 3 } },
  { id: 'ev-17', fieldUpdateId: 'fu-17', activityDescription: 'P104 erection commenced', location: 'Rack 3', progressPercent: 5, reportedDate: '2026-06-10', evidence: { sourceId: 'sms-2026-06-10b', sourceType: 'text', excerpt: 'P104 erection commenced at Rack 3 this morning.' } },
  { id: 'ev-18', fieldUpdateId: 'fu-18', activityDescription: 'P104 bolt-up completed', location: 'Rack 3', progressPercent: 100, reportedDate: '2026-06-15', evidence: { sourceId: 'dpr-2026-06-15', sourceType: 'dpr', excerpt: 'P104 bolt-up completed at Rack 3.', page: 2 } },
  { id: 'ev-19', fieldUpdateId: 'fu-19', activityDescription: 'All P104 punch points closed', location: 'Rack 3', progressPercent: 100, reportedDate: '2026-06-17', evidence: { sourceId: 'xls-progress-wk3', sourceType: 'excel', excerpt: 'All P104 punch points at Rack 3 closed.' } },
];
