import type { FieldUpdate } from '../types';

export const fieldUpdates: FieldUpdate[] = [
  { id: 'fu-1', projectId: 'proj-1', rawText: 'Structural steel Bay 1 erection substantially complete, touch-up welding remaining.', sourceFormat: 'dpr', timestamp: '2026-07-08T18:00:00Z', evidence: { sourceId: 'dpr-2026-07-08', sourceType: 'dpr', excerpt: 'Structural steel Bay 1 erection substantially complete, touch-up welding remaining.', page: 2 } },
  { id: 'fu-2', projectId: 'proj-1', rawText: 'Pipe rack erection at 60% - columns and first two tiers set.', sourceFormat: 'dpr', timestamp: '2026-07-18T18:00:00Z', evidence: { sourceId: 'dpr-2026-07-18', sourceType: 'dpr', excerpt: 'Pipe rack erection at 60% - columns and first two tiers set.', page: 1 } },
  { id: 'fu-3', projectId: 'proj-1', rawText: 'Line 24 erection at 45% today.', sourceFormat: 'text', timestamp: '2026-08-03T09:00:00Z', evidence: { sourceId: 'sms-2026-08-03', sourceType: 'text', excerpt: 'Line 24 erection at 45% today.' } },
  { id: 'fu-4', projectId: 'proj-1', rawText: 'Spool erected for Line 24, roughly halfway through the run.', sourceFormat: 'text', timestamp: '2026-08-02T16:30:00Z', evidence: { sourceId: 'sms-2026-08-02', sourceType: 'text', excerpt: 'Spool erected for Line 24, roughly halfway through the run.' } },
  { id: 'fu-5', projectId: 'proj-1', rawText: 'Crew reports pipe work near the pump skid substantially done, 60% by their count.', sourceFormat: 'voice', timestamp: '2026-08-04T14:00:00Z', evidence: { sourceId: 'voice-2026-08-04', sourceType: 'voice', excerpt: 'Crew reports pipe work near the pump skid substantially done, 60% by their count.' } },
  { id: 'fu-6', projectId: 'proj-1', rawText: 'New scope: contractor started demo of legacy scaffold tower near Bay 3, not on baseline schedule.', sourceFormat: 'text', timestamp: '2026-08-05T11:00:00Z', evidence: { sourceId: 'sms-2026-08-05', sourceType: 'text', excerpt: 'New scope: contractor started demo of legacy scaffold tower near Bay 3, not on baseline schedule.' } },
  { id: 'fu-7', projectId: 'proj-1', rawText: 'Foundation concrete pour Area A complete, cured, forms stripped.', sourceFormat: 'dpr', timestamp: '2026-06-25T18:00:00Z', evidence: { sourceId: 'dpr-2026-06-25', sourceType: 'dpr', excerpt: 'Foundation concrete pour Area A complete, cured, forms stripped.', page: 1 } },
  { id: 'fu-8', projectId: 'proj-1', rawText: 'Excavation Area B backfilled and compacted, ready for pour.', sourceFormat: 'excel', timestamp: '2026-06-13T18:00:00Z', evidence: { sourceId: 'xls-progress-wk24', sourceType: 'excel', excerpt: 'Excavation Area B: 100% complete, backfilled and compacted.' } },
  { id: 'fu-9', projectId: 'proj-1', rawText: 'Vessel setting Unit 100 at 55%, second vessel landed on foundation.', sourceFormat: 'excel', timestamp: '2026-07-14T18:00:00Z', evidence: { sourceId: 'xls-progress-wk29', sourceType: 'excel', excerpt: 'Vessel setting Unit 100: 55% complete.' } },
  { id: 'fu-10', projectId: 'proj-1', rawText: 'Electrical cable tray L5.4.1 reported complete on 2026-09-20, ahead of dependent activity start.', sourceFormat: 'text', timestamp: '2026-09-20T10:00:00Z', evidence: { sourceId: 'sms-2026-09-20', sourceType: 'text', excerpt: 'Electrical cable tray L5.4.1 reported complete on 2026-09-20.' } },
];
