/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedActivitiesRouteImport } from './routes/_authenticated/activities'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedConflictsRouteImport } from './routes/_authenticated/conflicts'
import { Route as AuthenticatedCriticalPathRouteImport } from './routes/_authenticated/critical-path'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedExecutionMemoryRouteImport } from './routes/_authenticated/execution-memory'
import { Route as AuthenticatedFieldUpdatesRouteImport } from './routes/_authenticated/field-updates'
import { Route as AuthenticatedImpactRouteImport } from './routes/_authenticated/impact'
import { Route as AuthenticatedRecoveryRouteImport } from './routes/_authenticated/recovery'
import { Route as AuthenticatedReviewRouteImport } from './routes/_authenticated/review'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSite3dRouteImport } from './routes/_authenticated/site-3d'
import { Route as AuthenticatedActivityIdRouteImport } from './routes/_authenticated/activity.$id'
import { Route as AuthenticatedEvidenceMatchIdRouteImport } from './routes/_authenticated/evidence.$matchId'
import { Route as AuthenticatedFieldUpdatesIdRouteImport } from './routes/_authenticated/field-updates.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivitiesRoute = AuthenticatedActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConflictsRoute = AuthenticatedConflictsRouteImport.update({
  id: '/conflicts',
  path: '/conflicts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCriticalPathRoute =
  AuthenticatedCriticalPathRouteImport.update({
    id: '/critical-path',
    path: '/critical-path',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExecutionMemoryRoute =
  AuthenticatedExecutionMemoryRouteImport.update({
    id: '/execution-memory',
    path: '/execution-memory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFieldUpdatesRoute =
  AuthenticatedFieldUpdatesRouteImport.update({
    id: '/field-updates',
    path: '/field-updates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImpactRoute = AuthenticatedImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecoveryRoute = AuthenticatedRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSite3dRoute = AuthenticatedSite3dRouteImport.update({
  id: '/site-3d',
  path: '/site-3d',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityIdRoute = AuthenticatedActivityIdRouteImport.update({
  id: '/activity/$id',
  path: '/activity/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEvidenceMatchIdRoute =
  AuthenticatedEvidenceMatchIdRouteImport.update({
    id: '/evidence/$matchId',
    path: '/evidence/$matchId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFieldUpdatesIdRoute =
  AuthenticatedFieldUpdatesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedFieldUpdatesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/conflicts': typeof AuthenticatedConflictsRoute
  '/critical-path': typeof AuthenticatedCriticalPathRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/execution-memory': typeof AuthenticatedExecutionMemoryRoute
  '/field-updates': typeof AuthenticatedFieldUpdatesRouteWithChildren
  '/impact': typeof AuthenticatedImpactRoute
  '/recovery': typeof AuthenticatedRecoveryRoute
  '/review': typeof AuthenticatedReviewRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/site-3d': typeof AuthenticatedSite3dRoute
  '/activity/$id': typeof AuthenticatedActivityIdRoute
  '/evidence/$matchId': typeof AuthenticatedEvidenceMatchIdRoute
  '/field-updates/$id': typeof AuthenticatedFieldUpdatesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/conflicts': typeof AuthenticatedConflictsRoute
  '/critical-path': typeof AuthenticatedCriticalPathRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/execution-memory': typeof AuthenticatedExecutionMemoryRoute
  '/field-updates': typeof AuthenticatedFieldUpdatesRouteWithChildren
  '/impact': typeof AuthenticatedImpactRoute
  '/recovery': typeof AuthenticatedRecoveryRoute
  '/review': typeof AuthenticatedReviewRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/site-3d': typeof AuthenticatedSite3dRoute
  '/activity/$id': typeof AuthenticatedActivityIdRoute
  '/evidence/$matchId': typeof AuthenticatedEvidenceMatchIdRoute
  '/field-updates/$id': typeof AuthenticatedFieldUpdatesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/activities': typeof AuthenticatedActivitiesRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/conflicts': typeof AuthenticatedConflictsRoute
  '/_authenticated/critical-path': typeof AuthenticatedCriticalPathRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/execution-memory': typeof AuthenticatedExecutionMemoryRoute
  '/_authenticated/field-updates': typeof AuthenticatedFieldUpdatesRouteWithChildren
  '/_authenticated/impact': typeof AuthenticatedImpactRoute
  '/_authenticated/recovery': typeof AuthenticatedRecoveryRoute
  '/_authenticated/review': typeof AuthenticatedReviewRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/site-3d': typeof AuthenticatedSite3dRoute
  '/_authenticated/activity/$id': typeof AuthenticatedActivityIdRoute
  '/_authenticated/evidence/$matchId': typeof AuthenticatedEvidenceMatchIdRoute
  '/_authenticated/field-updates/$id': typeof AuthenticatedFieldUpdatesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activities'
    | '/analytics'
    | '/audit'
    | '/conflicts'
    | '/critical-path'
    | '/dashboard'
    | '/documents'
    | '/execution-memory'
    | '/field-updates'
    | '/impact'
    | '/recovery'
    | '/review'
    | '/schedule'
    | '/settings'
    | '/site-3d'
    | '/activity/$id'
    | '/evidence/$matchId'
    | '/field-updates/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/activities'
    | '/analytics'
    | '/audit'
    | '/conflicts'
    | '/critical-path'
    | '/dashboard'
    | '/documents'
    | '/execution-memory'
    | '/field-updates'
    | '/impact'
    | '/recovery'
    | '/review'
    | '/schedule'
    | '/settings'
    | '/site-3d'
    | '/activity/$id'
    | '/evidence/$matchId'
    | '/field-updates/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/activities'
    | '/_authenticated/analytics'
    | '/_authenticated/audit'
    | '/_authenticated/conflicts'
    | '/_authenticated/critical-path'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/execution-memory'
    | '/_authenticated/field-updates'
    | '/_authenticated/impact'
    | '/_authenticated/recovery'
    | '/_authenticated/review'
    | '/_authenticated/schedule'
    | '/_authenticated/settings'
    | '/_authenticated/site-3d'
    | '/_authenticated/activity/$id'
    | '/_authenticated/evidence/$matchId'
    | '/_authenticated/field-updates/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activities': {
      id: '/_authenticated/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AuthenticatedActivitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conflicts': {
      id: '/_authenticated/conflicts'
      path: '/conflicts'
      fullPath: '/conflicts'
      preLoaderRoute: typeof AuthenticatedConflictsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/critical-path': {
      id: '/_authenticated/critical-path'
      path: '/critical-path'
      fullPath: '/critical-path'
      preLoaderRoute: typeof AuthenticatedCriticalPathRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/execution-memory': {
      id: '/_authenticated/execution-memory'
      path: '/execution-memory'
      fullPath: '/execution-memory'
      preLoaderRoute: typeof AuthenticatedExecutionMemoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/field-updates': {
      id: '/_authenticated/field-updates'
      path: '/field-updates'
      fullPath: '/field-updates'
      preLoaderRoute: typeof AuthenticatedFieldUpdatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impact': {
      id: '/_authenticated/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof AuthenticatedImpactRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recovery': {
      id: '/_authenticated/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof AuthenticatedRecoveryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/site-3d': {
      id: '/_authenticated/site-3d'
      path: '/site-3d'
      fullPath: '/site-3d'
      preLoaderRoute: typeof AuthenticatedSite3dRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity/$id': {
      id: '/_authenticated/activity/$id'
      path: '/activity/$id'
      fullPath: '/activity/$id'
      preLoaderRoute: typeof AuthenticatedActivityIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evidence/$matchId': {
      id: '/_authenticated/evidence/$matchId'
      path: '/evidence/$matchId'
      fullPath: '/evidence/$matchId'
      preLoaderRoute: typeof AuthenticatedEvidenceMatchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/field-updates/$id': {
      id: '/_authenticated/field-updates/$id'
      path: '/$id'
      fullPath: '/field-updates/$id'
      preLoaderRoute: typeof AuthenticatedFieldUpdatesIdRouteImport
      parentRoute: typeof AuthenticatedFieldUpdatesRoute
    }
  }
}

interface AuthenticatedFieldUpdatesRouteChildren {
  AuthenticatedFieldUpdatesIdRoute: typeof AuthenticatedFieldUpdatesIdRoute
}

const AuthenticatedFieldUpdatesRouteChildren: AuthenticatedFieldUpdatesRouteChildren =
  {
    AuthenticatedFieldUpdatesIdRoute: AuthenticatedFieldUpdatesIdRoute,
  }

const AuthenticatedFieldUpdatesRouteWithChildren =
  AuthenticatedFieldUpdatesRoute._addFileChildren(
    AuthenticatedFieldUpdatesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivitiesRoute: typeof AuthenticatedActivitiesRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedConflictsRoute: typeof AuthenticatedConflictsRoute
  AuthenticatedCriticalPathRoute: typeof AuthenticatedCriticalPathRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedExecutionMemoryRoute: typeof AuthenticatedExecutionMemoryRoute
  AuthenticatedFieldUpdatesRoute: typeof AuthenticatedFieldUpdatesRouteWithChildren
  AuthenticatedImpactRoute: typeof AuthenticatedImpactRoute
  AuthenticatedRecoveryRoute: typeof AuthenticatedRecoveryRoute
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSite3dRoute: typeof AuthenticatedSite3dRoute
  AuthenticatedActivityIdRoute: typeof AuthenticatedActivityIdRoute
  AuthenticatedEvidenceMatchIdRoute: typeof AuthenticatedEvidenceMatchIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivitiesRoute: AuthenticatedActivitiesRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedConflictsRoute: AuthenticatedConflictsRoute,
  AuthenticatedCriticalPathRoute: AuthenticatedCriticalPathRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedExecutionMemoryRoute: AuthenticatedExecutionMemoryRoute,
  AuthenticatedFieldUpdatesRoute: AuthenticatedFieldUpdatesRouteWithChildren,
  AuthenticatedImpactRoute: AuthenticatedImpactRoute,
  AuthenticatedRecoveryRoute: AuthenticatedRecoveryRoute,
  AuthenticatedReviewRoute: AuthenticatedReviewRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSite3dRoute: AuthenticatedSite3dRoute,
  AuthenticatedActivityIdRoute: AuthenticatedActivityIdRoute,
  AuthenticatedEvidenceMatchIdRoute: AuthenticatedEvidenceMatchIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
